import { strict as assert } from "node:assert";
import { readFileSync } from "node:fs";
import test from "node:test";
import { JSDOM } from "jsdom";

async function translateHelpFixture(html, translations) {
  const dom = new JSDOM(html, {
    url: "https://yukicoder.me/help",
    runScripts: "outside-only",
  });
  const { window } = dom;

  window.browser = { runtime: { getURL: (path) => path } };
  window.fetch = async () => ({
    ok: true,
    json: async () => ({ translations }),
  });
  window.eval(readFileSync("dist/src/content.js", "utf8"));
  await new Promise((resolve) => setTimeout(resolve, 0));

  return dom;
}

async function requestedDictionaryPaths(url) {
  const dom = new JSDOM("<body></body>", {
    url,
    runScripts: "outside-only",
  });
  const requestedPaths = [];
  const { window } = dom;

  window.browser = { runtime: { getURL: (path) => path } };
  window.fetch = async (path) => {
    requestedPaths.push(path);
    return { ok: true, json: async () => ({ translations: [] }) };
  };
  window.eval(readFileSync("dist/src/content.js", "utf8"));
  await new Promise((resolve) => setTimeout(resolve, 0));

  return requestedPaths;
}

test("help translations control spaces around inline elements", async () => {
  const dom = await translateHelpFixture(
    `
    <main id="content">
      <p id="tle">これは<b>TLE</b>になる可能性があります。</p>
      <p id="command"><code>/usr/local/bin/elixir -e Main.main</code> で実行されます。</p>
    </main>
  `,
    [
      {
        selector: "#content p",
        source: "これは",
        target: "이는 ",
      },
      {
        selector: "#content p",
        source: "になる可能性があります。",
        target: "가 될 가능성이 있습니다.",
      },
      {
        selector: "#content p",
        source: "で実行されます。",
        target: "으로 실행됩니다.",
        preserveBoundaryWhitespace: false,
      },
    ],
  );

  assert.equal(
    dom.window.document.querySelector("#tle").textContent,
    "이는 TLE가 될 가능성이 있습니다.",
  );
  assert.equal(
    dom.window.document.querySelector("#command").textContent,
    "/usr/local/bin/elixir -e Main.main으로 실행됩니다.",
  );
});

test("fixed UI attributes use selector-scoped exact replacement", async () => {
  const dom = new JSDOM(
    `
    <body>
      <main id="content">
        <i class="my_tooltip" title="ジャッジ＝通常・誤差を選んだときだけ表示されます。誤差判定の有無でさらに絞り込みます。"></i>
        <input id="s_search" type="submit" value="検索">
        <input id="outside" type="submit" value="検索">
      </main>
    </body>
  `,
    {
      url: "https://yukicoder.me/problems",
      runScripts: "outside-only",
    },
  );
  const { window } = dom;
  const problemTranslations = JSON.parse(
    readFileSync("translations/ko/problems.json", "utf8"),
  ).translations;
  const sharedTranslations = JSON.parse(
    readFileSync("translations/ko/shared.json", "utf8"),
  ).translations;

  window.browser = { runtime: { getURL: (path) => path } };
  window.fetch = async (path) => ({
    ok: true,
    json: async () => ({
      translations: path.endsWith("problems.json")
        ? problemTranslations
        : path.endsWith("shared.json")
          ? sharedTranslations
          : [],
    }),
  });
  window.eval(readFileSync("dist/src/content.js", "utf8"));
  await new Promise((resolve) => setTimeout(resolve, 0));

  assert.equal(
    window.document.querySelector("i.my_tooltip").title,
    "채점에서 일반·오차를 선택한 경우에만 표시됩니다. 오차 판정 여부로 다시 필터링합니다.",
  );
  assert.equal(window.document.querySelector("#s_search").value, "검색");
  assert.equal(window.document.querySelector("#outside").value, "検索");
});

test("mutation observer translates fixed UI generated by page scripts", async () => {
  const dom = new JSDOM(
    `
    <body>
      <main id="content">
        <span id="premium-remaining-time"></span>
      </main>
    </body>
  `,
    {
      url: "https://yukicoder.me/offer",
      runScripts: "outside-only",
    },
  );
  const { window } = dom;
  const offerTranslations = JSON.parse(
    readFileSync("translations/ko/offer_shared.json", "utf8"),
  ).translations;
  const sharedTranslations = JSON.parse(
    readFileSync("translations/ko/shared.json", "utf8"),
  ).translations;

  window.browser = { runtime: { getURL: (path) => path } };
  window.fetch = async (path) => ({
    ok: true,
    json: async () => ({
      translations: path.endsWith("offer_shared.json")
        ? offerTranslations
        : path.endsWith("shared.json")
          ? sharedTranslations
          : [],
    }),
  });
  window.eval(readFileSync("dist/src/content.js", "utf8"));
  await new Promise((resolve) => setTimeout(resolve, 0));

  window.document.querySelector("#premium-remaining-time").textContent =
    "2時間5分";
  await new Promise((resolve) => setTimeout(resolve, 0));

  assert.equal(
    window.document.querySelector("#premium-remaining-time").textContent,
    "2시간 5분",
  );

  const notification = window.document.createElement("div");
  notification.className = "noty_body";
  notification.textContent = "コピーしました";
  const copyButton = window.document.createElement("button");
  copyButton.className = "noty-copy-btn";
  copyButton.title = "コピー";
  window.document.body.append(notification, copyButton);
  await new Promise((resolve) => setTimeout(resolve, 0));

  assert.equal(notification.textContent, "복사했습니다");
  assert.equal(copyButton.title, "복사");
});

test("detail routes load their shared-layout and page dictionaries", async () => {
  const common = ["translations/ko/common.json"];
  const shared = ["translations/ko/shared.json"];
  const cases = [
    ["https://yukicoder.me/problems/12", ["problem"]],
    [
      "https://yukicoder.me/problems/12/favorite_users",
      ["problem_favorite_users"],
    ],
    [
      "https://yukicoder.me/problems/no/9000/statistics",
      ["problem", "problem_statistics"],
    ],
    [
      "https://yukicoder.me/contests/table-beta/614",
      ["contest", "contest_table", "contest_table_beta"],
    ],
    [
      "https://yukicoder.me/users/90/problems",
      ["user", "problems", "user_problems"],
    ],
    ["https://yukicoder.me/run/dac588ba7d541", ["run"]],
    ["https://yukicoder.me/wiki/stdio", ["wiki_shared", "wiki"]],
    ["https://yukicoder.me/wiki/guide/edit", ["wiki_shared", "wiki_edit"]],
  ];

  for (const [url, names] of cases) {
    assert.deepEqual(
      await requestedDictionaryPaths(url),
      [
        ...common,
        ...names.map((name) => `translations/ko/${name}.json`),
        ...shared,
      ],
      url,
    );
  }
});

test("favorite-user message preserves Korean particles around links", async () => {
  const dom = new JSDOM(
    `
    <body>
      <div id="favorite-users-message">
        <p>お気に入りにしたユーザーの一覧は、この問題の Writer / Tester と、
          <a>サイトサポーター</a>または<a>ワンデーサポーター</a>が表示できます。
        </p>
      </div>
    </body>
  `,
    {
      url: "https://yukicoder.me/problems/12/favorite_users",
      runScripts: "outside-only",
    },
  );
  const { window } = dom;
  const translations = JSON.parse(
    readFileSync("translations/ko/problem_favorite_users.json", "utf8"),
  ).translations;

  window.browser = { runtime: { getURL: (path) => path } };
  window.fetch = async (path) => ({
    ok: true,
    json: async () => ({
      translations: path.endsWith("problem_favorite_users.json")
        ? translations
        : [],
    }),
  });
  window.eval(readFileSync("dist/src/content.js", "utf8"));
  await new Promise((resolve) => setTimeout(resolve, 0));

  assert.equal(
    window.document.querySelector("#favorite-users-message p").textContent,
    "즐겨찾기에 추가한 사용자 목록은 이 문제의 Writer / Tester와, 사이트 서포터 또는 원데이 서포터가 볼 수 있습니다.",
  );
});

test("page-specific reviewed wording wins over a shared fallback", async () => {
  const dom = new JSDOM('<body><nav id="toplinks"><a>統計</a></nav></body>', {
    url: "https://yukicoder.me/contests/614",
    runScripts: "outside-only",
  });
  const { window } = dom;
  const dictionaries = {
    "translations/ko/common.json": [],
    "translations/ko/contest.json": [
      { selector: "#toplinks a", source: "統計", target: "통계" },
    ],
    "translations/ko/shared.json": [
      { selector: "#toplinks a", source: "統計", target: "📝 통계" },
    ],
  };

  window.browser = { runtime: { getURL: (path) => path } };
  window.fetch = async (path) => ({
    ok: true,
    json: async () => ({ translations: dictionaries[path] }),
  });
  window.eval(readFileSync("dist/src/content.js", "utf8"));
  await new Promise((resolve) => setTimeout(resolve, 0));

  assert.equal(
    window.document.querySelector("#toplinks a").textContent,
    "통계",
  );
});
